apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-schema
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/ss-system: ""
      tolerations:
        - key: node-role.kubernetes.io/ss-system
          operator: Exists
          effect: NoSchedule
