apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/ss-system: ""
      tolerations:
        - key: node-role.kubernetes.io/ss-system
          operator: Exists
          effect: NoSchedule
